#! /bin/sh

DIARY="~/Documents/Diary"
MONTH=$(date +%B)
DATE=$(date +"%d-%A")

new () {
    mkdir $DIARY/$MONTH
    alacritty -e vim /$DIARY/$MONTH/$Date.md
}

list () {
    cd $DIARY
    sel=$(find * -type f | sort -M | dmenu -l 15 -p "Diary")
    if [[ $sel == "" ]]; then
	exit 0 #si se presiona ESC, el script termina
    else
	alacritty -e vim $sel
    fi
}

case $1 in
    'new') new;;
    'list') list;;
esac

