#!/bin/bash


# Set decoration geometry
berryc border_width       4
berryc inner_border_width 2
berryc title_height       1
berryc top_gap            2
berryc edge_gap 3 3 3 3

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   2ea564
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-12"
berryc decorate_new "false"


# picom --config $HOME/.config/berry/picom.conf &
feh --bg-fill $HOME/Pictures/Wallpapers/dog-hifi-human.png &
conky -c $HOME/.conkyrc &
sxhkd -c $HOME/.config/berry/sxhkdrc &
mpd &
